version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:latest'
    user: '1024:0'
    volumes:
      - '/volume1/docker/admin_mairadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'docker.io/bitnami/wordpress-nginx:latest'
    user: '1024:0'
    ports:
      - '32832:8080'
      - '32833:8443'
    volumes:
      - '/volume1/docker/admin_wordpress_data:/bitnami/wordpress'
      - './certs:/opt/bitnami/nginx/conf/bitnami/certs'
      - './wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_SCHEME=https
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
